Title: python-exec package move
Author: Michał Górny <mgorny@gentoo.org>
Content-Type: text/plain
Posted: 2013-11-07
Revision: 1
News-Item-Format: 1.0
Display-If-Installed: dev-python/python-exec

Due to the recent issues which caused dev-python/python-exec:0 to be
removed prematurely [1], we had to perform an urgent package move.
Since we could not use the automatic updates support in portage, users
will notice two python-exec packages and possibly blockers.

Currently, dev-lang/python-exec is the real package that contains
python-exec and that will be used in the future. dev-python/python-exec
is a virtual package that is kept for compatibility with dependencies
in already-installed packages.

In the most favorable scenario, the package will be upgraded correctly
on your next world update if you use the '--deep' (-D) and '--update'
(-u) options. If you don't want to perform a complete world update
or if it fails for you, you may as well manually upgrade
dev-python/python-exec:

  emerge -1 dev-python/python-exec

This will cause portage to update both python-exec packages and resolve
the blockers properly.

Please note that if you have applied any kind of package-specific
modifications to dev-python/python-exec (such as applying keywords
through 'package.accept_keywords'), you will need to copy them to
dev-lang/python-exec as well.

If you have applied keywords to dev-python/python-exec in order
to unmask Python 3.3 on a stable system, please consider removing
the keywords and reading our wiki page that explains how to properly
unmask USE flags [2].

We apologize for all the inconveniences. If you have any more issues
with python-exec, please do not hesitate to contact as at #gentoo-python
IRC channel (@freenode) or the gentoo-python@lists.gentoo.org mailing
list.

[1]:https://bugs.gentoo.org/show_bug.cgi?id=489440
[2]:https://wiki.gentoo.org/wiki/Unmasking_non-stable_Python_implementations
